[versions]
kotlin = "1.8.0"
androidGradlePlugin = "8.1.2"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }